/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

import admin.ProfilAdmin;
import data.AdminController;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import main.Login;

/**
 *
 * @author SMKN4
 */
public class ProfilBankPassword extends javax.swing.JFrame {

    /**
     * Creates new form HomeAdmin
     */
    Connection koneksi;
    public ProfilBankPassword() {
        initComponents();
        koneksi = main.DatabaseConnection.getKoneksi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSimpan = new javax.swing.JButton();
        tvPassNewRetry = new javax.swing.JLabel();
        tvPassNew = new javax.swing.JLabel();
        tvPassOld = new javax.swing.JLabel();
        edtPassNew = new javax.swing.JPasswordField();
        separator3 = new javax.swing.JSeparator();
        edtPassNewRetry = new javax.swing.JPasswordField();
        separator4 = new javax.swing.JSeparator();
        edtPassOld = new javax.swing.JPasswordField();
        separator2 = new javax.swing.JSeparator();
        btnBack = new javax.swing.JLabel();
        menuLaporan = new javax.swing.JLabel();
        menuProfil = new javax.swing.JLabel();
        menuHome = new javax.swing.JLabel();
        tvNama = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSimpan.setBackground(new java.awt.Color(68, 185, 235));
        btnSimpan.setText("Simpan");
        btnSimpan.setBorder(null);
        btnSimpan.setOpaque(false);
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 110, 40));

        tvPassNewRetry.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tvPassNewRetry.setForeground(new java.awt.Color(68, 185, 255));
        tvPassNewRetry.setText("Tulis Ulang Password Baru");
        getContentPane().add(tvPassNewRetry, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, -1));

        tvPassNew.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tvPassNew.setForeground(new java.awt.Color(68, 185, 255));
        tvPassNew.setText("Password Baru");
        getContentPane().add(tvPassNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        tvPassOld.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tvPassOld.setForeground(new java.awt.Color(68, 185, 255));
        tvPassOld.setText("Password Lama");
        getContentPane().add(tvPassOld, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        edtPassNew.setBackground(new java.awt.Color(255, 255, 255));
        edtPassNew.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edtPassNew.setForeground(new java.awt.Color(68, 185, 255));
        edtPassNew.setBorder(null);
        edtPassNew.setCaretColor(new java.awt.Color(68, 185, 255));
        edtPassNew.setOpaque(false);
        getContentPane().add(edtPassNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 280, 50));

        separator3.setForeground(new java.awt.Color(68, 185, 235));
        getContentPane().add(separator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 280, 10));

        edtPassNewRetry.setBackground(new java.awt.Color(255, 255, 255));
        edtPassNewRetry.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edtPassNewRetry.setForeground(new java.awt.Color(68, 185, 255));
        edtPassNewRetry.setBorder(null);
        edtPassNewRetry.setCaretColor(new java.awt.Color(68, 185, 255));
        edtPassNewRetry.setOpaque(false);
        getContentPane().add(edtPassNewRetry, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 280, 50));

        separator4.setForeground(new java.awt.Color(68, 185, 235));
        getContentPane().add(separator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 280, 10));

        edtPassOld.setBackground(new java.awt.Color(255, 255, 255));
        edtPassOld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edtPassOld.setForeground(new java.awt.Color(68, 185, 255));
        edtPassOld.setBorder(null);
        edtPassOld.setCaretColor(new java.awt.Color(68, 185, 255));
        edtPassOld.setOpaque(false);
        getContentPane().add(edtPassOld, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 280, 50));

        separator2.setForeground(new java.awt.Color(68, 185, 235));
        getContentPane().add(separator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 280, 10));

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnBack.setText("< Batal");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        menuLaporan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        menuLaporan.setForeground(new java.awt.Color(255, 255, 255));
        menuLaporan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuLaporan.setText("Laporan");
        getContentPane().add(menuLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 255, 265, 60));

        menuProfil.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        menuProfil.setForeground(new java.awt.Color(255, 255, 255));
        menuProfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuProfil.setText("Profil");
        getContentPane().add(menuProfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 195, 265, 60));

        menuHome.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        menuHome.setForeground(new java.awt.Color(255, 255, 255));
        menuHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuHome.setText("Beranda");
        getContentPane().add(menuHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 135, 265, 60));

        tvNama.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tvNama.setForeground(new java.awt.Color(255, 255, 255));
        tvNama.setText("Nama");
        getContentPane().add(tvNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, -1));

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/01_Menu2Admin.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        ProfilBank i = new ProfilBank();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        if (edtPassOld.getText().equals("") || edtPassNew.getText().equals("") || edtPassNewRetry.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Data tidak boleh Kosong");
        } else {
            if (edtPassOld.getText().equals(AdminController.getPassword())) {
                if (edtPassNew.getText().equals(edtPassNewRetry.getText())) {
                    AdminController.setPassword(edtPassNew.getText().toString());
                    try {
                        Statement stmt = koneksi.createStatement();
                        String query = "UPDATE admin SET password = '"+AdminController.getPassword()+"' WHERE id_admin = "+AdminController.getIdAdmin()+"";
                        System.out.println(query);
                        int berhasil = stmt.executeUpdate(query);
                        if (berhasil == 1) {
                            JOptionPane.showMessageDialog(null, "Setting Berhasil");
                            ProfilBank i = new ProfilBank();
                            i.setVisible(true);
                            this.dispose();
                        } else {
                            JOptionPane.showMessageDialog(null, "Setting Gagal");
                        }
                    } catch (SQLException e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(null, "Terjadi kesalahan pada Database");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Periksa Kembali Inputan Anda");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Password Salah");
            }
        }
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        int p = JOptionPane.showConfirmDialog(null, "Anda Yakin Ingin Keluar ?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (p == 0) {
            Login i = new Login();
            i.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfilBankPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfilBankPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfilBankPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfilBankPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfilBankPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JPasswordField edtPassNew;
    private javax.swing.JPasswordField edtPassNewRetry;
    private javax.swing.JPasswordField edtPassOld;
    private javax.swing.JLabel menuHome;
    private javax.swing.JLabel menuLaporan;
    private javax.swing.JLabel menuProfil;
    private javax.swing.JSeparator separator2;
    private javax.swing.JSeparator separator3;
    private javax.swing.JSeparator separator4;
    private javax.swing.JLabel tvNama;
    private javax.swing.JLabel tvPassNew;
    private javax.swing.JLabel tvPassNewRetry;
    private javax.swing.JLabel tvPassOld;
    // End of variables declaration//GEN-END:variables
}
