/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author SMKN4
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    String username = "";
    String password = "";
    String rPassword = "";
    String nama = "";
    String kodeAkses = "";
    Connection koneksi;
    public Register() {
        initComponents();
        koneksi = DatabaseConnection.getKoneksi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edtRetryPassword = new javax.swing.JPasswordField();
        edtPassword = new javax.swing.JPasswordField();
        edtUsername = new javax.swing.JTextField();
        edtCodeAccess = new javax.swing.JTextField();
        edtName = new javax.swing.JTextField();
        btnRegister = new javax.swing.JLabel();
        tvQuestion = new javax.swing.JLabel();
        btnToLogin = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi PPOB");
        setMaximumSize(new java.awt.Dimension(950, 500));
        setMinimumSize(new java.awt.Dimension(950, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edtRetryPassword.setBackground(new java.awt.Color(68, 185, 235));
        edtRetryPassword.setForeground(new java.awt.Color(255, 255, 255));
        edtRetryPassword.setBorder(null);
        edtRetryPassword.setCaretColor(new java.awt.Color(255, 255, 255));
        edtRetryPassword.setOpaque(false);
        getContentPane().add(edtRetryPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 185, 30));

        edtPassword.setBackground(new java.awt.Color(68, 185, 235));
        edtPassword.setForeground(new java.awt.Color(255, 255, 255));
        edtPassword.setBorder(null);
        edtPassword.setCaretColor(new java.awt.Color(255, 255, 255));
        edtPassword.setOpaque(false);
        getContentPane().add(edtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 178, 185, 30));

        edtUsername.setBackground(new java.awt.Color(68, 185, 235));
        edtUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edtUsername.setForeground(new java.awt.Color(255, 255, 255));
        edtUsername.setBorder(null);
        edtUsername.setCaretColor(new java.awt.Color(255, 255, 255));
        edtUsername.setOpaque(false);
        getContentPane().add(edtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 190, 30));

        edtCodeAccess.setBackground(new java.awt.Color(68, 185, 235));
        edtCodeAccess.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edtCodeAccess.setForeground(new java.awt.Color(255, 255, 255));
        edtCodeAccess.setBorder(null);
        edtCodeAccess.setCaretColor(new java.awt.Color(255, 255, 255));
        edtCodeAccess.setOpaque(false);
        getContentPane().add(edtCodeAccess, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 190, 30));

        edtName.setBackground(new java.awt.Color(68, 185, 235));
        edtName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edtName.setForeground(new java.awt.Color(255, 255, 255));
        edtName.setBorder(null);
        edtName.setCaretColor(new java.awt.Color(255, 255, 255));
        edtName.setOpaque(false);
        getContentPane().add(edtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 175, 190, 30));

        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(68, 185, 235));
        btnRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegister.setText("Register");
        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegisterMouseClicked(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 372, 210, 60));

        tvQuestion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tvQuestion.setForeground(new java.awt.Color(255, 255, 255));
        tvQuestion.setText("Sudah Punya Akun ?");
        getContentPane().add(tvQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, -1, -1));

        btnToLogin.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnToLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnToLogin.setText("Login");
        btnToLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnToLoginMouseClicked(evt);
            }
        });
        getContentPane().add(btnToLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/01_MainRegister.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnToLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnToLoginMouseClicked
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnToLoginMouseClicked

    private void btnRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseClicked
        getData();
        if (username.equals("") || password.equals("") || rPassword.equals("") || nama.equals("")) {
            JOptionPane.showMessageDialog(null, "Silahkan masukkan Data terlebih dahulu");
        } else {
            if (password.equals(rPassword)) {
                if (kodeAkses.equals("")) {
                    try {
                        Statement stmt = koneksi.createStatement();
                        String query = "INSERT INTO pelanggan(username, password, nama_pelanggan, id_tarif)"
                                + " VALUES ('"+username+"', '"+password+"', '"+nama+"', 1)";
                        System.out.println(query);
                        int berhasil = stmt.executeUpdate(query);
                        if (berhasil == 1) {
                            JOptionPane.showMessageDialog(null, "Akun berhasil dibuat");
                        } else {
                            JOptionPane.showMessageDialog(null, "Akun gagal dibuat");
                        }
                    } catch (SQLException e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(null, "Terjadi kesalahan pada Database");
                    }
                } else if (kodeAkses.equals("12345")) {
                    try {
                        Statement stmt = koneksi.createStatement();
                        String query = "INSERT INTO admin(username, password, nama_admin, id_level)"
                                + " VALUES ('"+username+"', '"+password+"', '"+nama+"', 1)";
                        System.out.println(query);
                        int berhasil = stmt.executeUpdate(query);
                        if (berhasil == 1) {
                            JOptionPane.showMessageDialog(null, "Akun berhasil dibuat");
                        } else {
                            JOptionPane.showMessageDialog(null, "Akun gagal dibuat");
                        }
                    } catch (SQLException e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(null, "Terjadi kesalahan pada Database");
                    }
                } else if (!kodeAkses.equals("12345")) {
                    JOptionPane.showMessageDialog(null, "Kode Akses Salah");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Silahkan Cek Ulang Password");
            }
        }
    }//GEN-LAST:event_btnRegisterMouseClicked
    
    private void getData() {
        username = edtUsername.getText().toString();
        password = edtPassword.getText().toString();
        rPassword = edtRetryPassword.getText().toString();
        kodeAkses = edtCodeAccess.getText().toString();
        nama = edtName.getText().toString();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btnRegister;
    private javax.swing.JLabel btnToLogin;
    private javax.swing.JTextField edtCodeAccess;
    private javax.swing.JTextField edtName;
    private javax.swing.JPasswordField edtPassword;
    private javax.swing.JPasswordField edtRetryPassword;
    private javax.swing.JTextField edtUsername;
    private javax.swing.JLabel tvQuestion;
    // End of variables declaration//GEN-END:variables
}
