/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.Login;

/**
 *
 * @author SMKN4
 */
public class HomeAdmin extends javax.swing.JFrame {

    /**
     * Creates new form HomeAdmin
     */
    Connection koneksi;
    public HomeAdmin() {
        initComponents();
        koneksi = main.DatabaseConnection.getKoneksi();
        showData();
        tvNama.setText(data.AdminController.getNamaAdmin());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleFrame = new javax.swing.JLabel();
        btnCekPembayaran = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPembayaran = new javax.swing.JTable();
        separator = new javax.swing.JSeparator();
        menuLaporan = new javax.swing.JLabel();
        menuKelola = new javax.swing.JLabel();
        menuProfil = new javax.swing.JLabel();
        menuHome = new javax.swing.JLabel();
        tvNama = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(950, 550));
        setMinimumSize(new java.awt.Dimension(950, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleFrame.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleFrame.setForeground(new java.awt.Color(68, 185, 235));
        titleFrame.setText("Validasi Pembayaran");
        getContentPane().add(titleFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));

        btnCekPembayaran.setBackground(new java.awt.Color(68, 185, 235));
        btnCekPembayaran.setText("Cek Pembayaran");
        btnCekPembayaran.setBorder(null);
        btnCekPembayaran.setOpaque(false);
        btnCekPembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCekPembayaranMouseClicked(evt);
            }
        });
        getContentPane().add(btnCekPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 150, 40));

        tblPembayaran.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tblPembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "No Kwh", "Bulan Bayar", "Tanggal bayar", "Total Bayar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPembayaranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPembayaran);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 610, 260));

        separator.setForeground(new java.awt.Color(68, 185, 235));
        getContentPane().add(separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 180, 3));

        menuLaporan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        menuLaporan.setForeground(new java.awt.Color(255, 255, 255));
        menuLaporan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuLaporan.setText("Laporan");
        menuLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLaporanMouseClicked(evt);
            }
        });
        getContentPane().add(menuLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 315, 265, 60));

        menuKelola.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        menuKelola.setForeground(new java.awt.Color(255, 255, 255));
        menuKelola.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuKelola.setText("Kelola Data");
        menuKelola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuKelolaMouseClicked(evt);
            }
        });
        getContentPane().add(menuKelola, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 255, 265, 60));

        menuProfil.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        menuProfil.setForeground(new java.awt.Color(255, 255, 255));
        menuProfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuProfil.setText("Profil");
        menuProfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuProfilMouseClicked(evt);
            }
        });
        getContentPane().add(menuProfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 195, 265, 60));

        menuHome.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        menuHome.setForeground(new java.awt.Color(255, 255, 255));
        menuHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuHome.setText("Beranda");
        getContentPane().add(menuHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 135, 265, 60));

        tvNama.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tvNama.setForeground(new java.awt.Color(255, 255, 255));
        tvNama.setText("Nama");
        getContentPane().add(tvNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, -1));

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/01_Menu1Admin.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        int p = JOptionPane.showConfirmDialog(null, "Anda Yakin Ingin Keluar ?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (p == 0) {
            Login i = new Login();
            i.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnCekPembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCekPembayaranMouseClicked
        String noKwh = tblPembayaran.getValueAt(baris, 1).toString();
        String bulan = tblPembayaran.getValueAt(baris, 2).toString();
        HomeAdminValidasi validasi = new HomeAdminValidasi(noKwh, bulan);
        validasi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCekPembayaranMouseClicked
    int baris;
    private void tblPembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPembayaranMouseClicked
        baris = tblPembayaran.getSelectedRow();
    }//GEN-LAST:event_tblPembayaranMouseClicked

    private void menuProfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuProfilMouseClicked
        ProfilAdmin i = new ProfilAdmin();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuProfilMouseClicked

    private void menuKelolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuKelolaMouseClicked
        KelolaAdmin i = new KelolaAdmin();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuKelolaMouseClicked

    private void menuLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLaporanMouseClicked
        LaporanAdmin i = new LaporanAdmin();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuLaporanMouseClicked

    DefaultTableModel dtm;
    private void showData() {
        String[] kolom = {"No", "No kwh", "Bulan Bayar", "Tanggal Bayar", "Total Bayar"};
        dtm = new DefaultTableModel(null, kolom);
        int no = 1;
        try {
            Statement st = koneksi.createStatement();
            String q = "SELECT * FROM pembayaran, tagihan, penggunaan, pelanggan WHERE "
                    + "(penggunaan.id_pelanggan = pelanggan.id_pelanggan) AND "
                    + "(tagihan.id_penggunaan = penggunaan.id_penggunaan) AND "
                    + "(pembayaran.id_tagihan = tagihan.id_tagihan) AND "
                    + "(tagihan.status != 'Sudah Bayar')";
            
            ResultSet rs =st.executeQuery(q);
            while (rs.next()) {
                String noKwh = rs.getString("nomor_kwh");
                String bulanBayar = rs.getString("bulan_bayar");
                String tanggalBayar = rs.getString("tanggal_pembayaran");
                int totalBayar = rs.getInt("total_bayar");
                dtm.addRow(new String[]{no + "", noKwh, bulanBayar, tanggalBayar, totalBayar + ""});
                no++;
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        tblPembayaran.setModel(dtm);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnCekPembayaran;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel menuHome;
    private javax.swing.JLabel menuKelola;
    private javax.swing.JLabel menuLaporan;
    private javax.swing.JLabel menuProfil;
    private javax.swing.JSeparator separator;
    private javax.swing.JTable tblPembayaran;
    private javax.swing.JLabel titleFrame;
    private javax.swing.JLabel tvNama;
    // End of variables declaration//GEN-END:variables
}
