/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import main.Login;

/**
 *
 * @author SMKN4
 */
public class HomeAdminValidasi extends javax.swing.JFrame {

    /**
     * Creates new form HomeAdmin
     */
    Connection koneksi;
    int idTagihan = 0;
    int idPembayaran = 0;
    public HomeAdminValidasi( String noKwh, String bulanBayar) {
        initComponents();
        koneksi = main.DatabaseConnection.getKoneksi();
        tvNama.setText(data.AdminController.getNamaAdmin());
        showData(noKwh, bulanBayar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnValidasiPembayaran = new javax.swing.JButton();
        tvTotalBayar = new javax.swing.JLabel();
        tvBiayaAdmin = new javax.swing.JLabel();
        tvJumlahTagihan = new javax.swing.JLabel();
        tvJumlahMeter = new javax.swing.JLabel();
        tvMeterAkhir = new javax.swing.JLabel();
        tvMeterAwal = new javax.swing.JLabel();
        tvBulanBayar = new javax.swing.JLabel();
        tvTanggalBayar = new javax.swing.JLabel();
        tvDayaTarif = new javax.swing.JLabel();
        tvAlamat = new javax.swing.JLabel();
        tvNoKwh = new javax.swing.JLabel();
        tvNamaPelanggan = new javax.swing.JLabel();
        titleFrame1 = new javax.swing.JLabel();
        separator1 = new javax.swing.JSeparator();
        titleFrame = new javax.swing.JLabel();
        separator = new javax.swing.JSeparator();
        btnBack = new javax.swing.JLabel();
        menuLaporan = new javax.swing.JLabel();
        menuKelola = new javax.swing.JLabel();
        menuProfil = new javax.swing.JLabel();
        menuHome = new javax.swing.JLabel();
        tvNama = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnValidasiPembayaran.setBackground(new java.awt.Color(68, 185, 235));
        btnValidasiPembayaran.setText("Validasi Pembayaran");
        btnValidasiPembayaran.setBorder(null);
        btnValidasiPembayaran.setOpaque(false);
        btnValidasiPembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnValidasiPembayaranMouseClicked(evt);
            }
        });
        getContentPane().add(btnValidasiPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 150, 40));

        tvTotalBayar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        tvTotalBayar.setText("Total Bayar : Rp. 203500");
        getContentPane().add(tvTotalBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, -1, -1));

        tvBiayaAdmin.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tvBiayaAdmin.setText("Biaya Admin : Rp. 2500");
        getContentPane().add(tvBiayaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, -1, -1));

        tvJumlahTagihan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tvJumlahTagihan.setText("Jumlah Tagihan : Rp. 201000");
        getContentPane().add(tvJumlahTagihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, -1, -1));

        tvJumlahMeter.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tvJumlahMeter.setText("Jumlah Meter : 2204");
        getContentPane().add(tvJumlahMeter, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, -1));

        tvMeterAkhir.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tvMeterAkhir.setText("Meter Akhir : 2304");
        getContentPane().add(tvMeterAkhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        tvMeterAwal.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tvMeterAwal.setText("Meter Awal : 100");
        getContentPane().add(tvMeterAwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, -1));

        tvBulanBayar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tvBulanBayar.setText("Bulan Bayar : April 2019");
        getContentPane().add(tvBulanBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, -1));

        tvTanggalBayar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tvTanggalBayar.setText("18/05/2019");
        getContentPane().add(tvTanggalBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, -1, -1));

        tvDayaTarif.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tvDayaTarif.setText("Daya Rumah : R1M/240V");
        getContentPane().add(tvDayaTarif, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        tvAlamat.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tvAlamat.setText("Alamat : Alamat Pelanggan");
        getContentPane().add(tvAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        tvNoKwh.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tvNoKwh.setText("No Kwh : 1234567890");
        getContentPane().add(tvNoKwh, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        tvNamaPelanggan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tvNamaPelanggan.setText("Nama : Nama Pelanggan");
        getContentPane().add(tvNamaPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        titleFrame1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleFrame1.setForeground(new java.awt.Color(68, 185, 235));
        titleFrame1.setText("Detail Pembayaran");
        getContentPane().add(titleFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        separator1.setForeground(new java.awt.Color(68, 185, 235));
        getContentPane().add(separator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 160, 10));

        titleFrame.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleFrame.setForeground(new java.awt.Color(68, 185, 235));
        titleFrame.setText("Data Pelanggan");
        getContentPane().add(titleFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        separator.setForeground(new java.awt.Color(68, 185, 235));
        getContentPane().add(separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 142, 140, 10));

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnBack.setText("< Batal");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        menuLaporan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        menuLaporan.setForeground(new java.awt.Color(255, 255, 255));
        menuLaporan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuLaporan.setText("Laporan");
        getContentPane().add(menuLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 315, 265, 60));

        menuKelola.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        menuKelola.setForeground(new java.awt.Color(255, 255, 255));
        menuKelola.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuKelola.setText("Kelola Data");
        getContentPane().add(menuKelola, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 255, 265, 60));

        menuProfil.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        menuProfil.setForeground(new java.awt.Color(255, 255, 255));
        menuProfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuProfil.setText("Profil");
        getContentPane().add(menuProfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 195, 265, 60));

        menuHome.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        menuHome.setForeground(new java.awt.Color(255, 255, 255));
        menuHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuHome.setText("Beranda");
        getContentPane().add(menuHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 135, 265, 60));

        tvNama.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tvNama.setForeground(new java.awt.Color(255, 255, 255));
        tvNama.setText("Nama");
        getContentPane().add(tvNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, -1));

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/01_Menu1Admin.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
       int p = JOptionPane.showConfirmDialog(null, "Anda Yakin Ingin Keluar ?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (p == 0) {
            Login i = new Login();
            i.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        HomeAdmin i = new HomeAdmin();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnValidasiPembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnValidasiPembayaranMouseClicked
        try {
            Statement stmt = koneksi.createStatement();
            String query = "UPDATE tagihan SET status = 'Sudah Bayar' WHERE id_tagihan = "+idTagihan+"";
            String que = "UPDATE pembayaran SET id_admin = "+ data.AdminController.getIdAdmin() +" WHERE id_pembayaran = "+idPembayaran+"";
            System.out.println(query);
            int berhasil = stmt.executeUpdate(query);
            int berhasil2 = stmt.executeUpdate(que);
            if (berhasil == 1 && berhasil2 == 1) {
                JOptionPane.showMessageDialog(null, "Berhasil Memvalidasi Pembayaran");
                HomeAdmin i = new HomeAdmin();
                i.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Gagal Memvalidasi Pembayaran");
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan pada Database");
        }
                        
    }//GEN-LAST:event_btnValidasiPembayaranMouseClicked

    private void showData(String noKwh, String bulanBayar) {
        String q = "SELECT * FROM pembayaran, tagihan, penggunaan, pelanggan, tarif WHERE "
                    + "(penggunaan.id_pelanggan = pelanggan.id_pelanggan) AND "
                    + "(tagihan.id_penggunaan = penggunaan.id_penggunaan) AND "
                    + "(pembayaran.id_tagihan = tagihan.id_tagihan) AND (pelanggan.id_tarif = tarif.id_tarif) AND"
                    + "(tagihan.status != 'Sudah Bayar') AND (bulan_bayar = '"+bulanBayar+"') AND "
                    + "(nomor_kwh = '"+noKwh+"')";
        try {
            Statement stmt = koneksi.createStatement();
            ResultSet rs = stmt.executeQuery(q);
            if (rs.next()) {
                tvNamaPelanggan.setText("Nama : " + rs.getString("nama_pelanggan"));
                tvNoKwh.setText("No Kwh : " + rs.getString("nomor_kwh"));
                tvAlamat.setText("Alamat : " + rs.getString("alamat"));
                tvDayaTarif.setText("Daya Rumah : " + rs.getString("daya"));
                tvTanggalBayar.setText(rs.getString("tanggal_pembayaran"));
                tvBulanBayar.setText("Bulan Bayar : " + rs.getString("bulan_bayar"));
                tvMeterAwal.setText("Meter Awal : " + rs.getInt("meter_awal"));
                tvMeterAkhir.setText("Meter Akhir : " + rs.getInt("meter_akhir"));
                tvJumlahMeter.setText("Jumlah Meter : " + rs.getInt("jumlah_meter"));
                int jMeter = rs.getInt("jumlah_meter");
                int tarif = rs.getInt("tarifperkwh");
                int jTagihan = jMeter * tarif;
                tvJumlahTagihan.setText("Jumlah Tagihan : " + jTagihan);
                tvBiayaAdmin.setText("Biaya Admin : " + rs.getString("biaya_admin"));
                tvTotalBayar.setText("Total Bayar : " + rs.getInt("total_bayar"));
                idPembayaran = rs.getInt("pembayaran.id_pembayaran");
                idTagihan = rs.getInt("tagihan.id_tagihan");
            }
        } catch (SQLException e) {
            e.getCause();
            e.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeAdminValidasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeAdminValidasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeAdminValidasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeAdminValidasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HomeAdminValidasi().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JButton btnValidasiPembayaran;
    private javax.swing.JLabel menuHome;
    private javax.swing.JLabel menuKelola;
    private javax.swing.JLabel menuLaporan;
    private javax.swing.JLabel menuProfil;
    private javax.swing.JSeparator separator;
    private javax.swing.JSeparator separator1;
    private javax.swing.JLabel titleFrame;
    private javax.swing.JLabel titleFrame1;
    private javax.swing.JLabel tvAlamat;
    private javax.swing.JLabel tvBiayaAdmin;
    private javax.swing.JLabel tvBulanBayar;
    private javax.swing.JLabel tvDayaTarif;
    private javax.swing.JLabel tvJumlahMeter;
    private javax.swing.JLabel tvJumlahTagihan;
    private javax.swing.JLabel tvMeterAkhir;
    private javax.swing.JLabel tvMeterAwal;
    private javax.swing.JLabel tvNama;
    private javax.swing.JLabel tvNamaPelanggan;
    private javax.swing.JLabel tvNoKwh;
    private javax.swing.JLabel tvTanggalBayar;
    private javax.swing.JLabel tvTotalBayar;
    // End of variables declaration//GEN-END:variables
}
